"""Check the Python port against vectors generated by running the official
app's own JavaScript (CryptoJS + packet builders) in Node."""
import importlib.util
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).parent
_spec = importlib.util.spec_from_file_location(
    "cube_protocol", HERE.parent / "custom_components" / "laserworld_cube" / "protocol.py")
p = importlib.util.module_from_spec(_spec)
sys.modules["cube_protocol"] = p
_spec.loader.exec_module(p)
V = json.loads((HERE / "vectors.json").read_text())


def test_key_table_matches_app():
    assert list(p.KEY_TABLE) == V["key_table"]


def test_default_key_iv():
    for n in V["names"]:
        key, iv = p.default_key_iv(n["name"])
        assert key.decode() == n["key"] and iv.decode() == n["iv"], n["name"]


def test_encrypt_decrypt_match_app():
    gw = V["gateway"]
    for c in V["crypt"]:
        if c["mode"] == "default":
            key, iv = p.default_key_iv("BLEAPP_847E")
        else:
            at = 1 if c["mode"] == "activated" else 0
            key, iv = p.session_key_iv(at, gw["productKey"], gw["deviceKey"], gw["deviceSecret"])
        assert key.decode() == c["key"] and iv.decode() == c["iv"]
        plain = bytes(c["plain"])
        assert p.encrypt(plain, key, iv) == bytes(c["enc"]), (c["mode"], len(plain))
        # app's decrypt returns zero padded data; compare on the original length
        assert p.decrypt(bytes(c["enc"]), key, iv)[: len(plain)] == plain
        assert p.decrypt(bytes(c["enc"]), key, iv) == bytes(c["dec"])


def test_simple_frames():
    for s in V["simple"]:
        assert p.build_simple(s["f"], s["a"]) == bytes(s["frame"])


def test_transfer_frames():
    for t in V["transfer"]:
        data = bytes(t["data"]) if t["data"] is not None else None
        got = p.build_transfer(t["f"], t["a"], data, data_format=t["fmt"], timestamp=t["ts"])
        assert got == bytes(t["frame"])


def test_run_params_bytes():
    assert p.build_run_params(V["params"]) == bytes(V["params_bytes"])


def test_handshake_frames():
    for h in V["handshake"]:
        assert p.build_handshake(h["user"], tuple(h["ver"]), bytes(h["rnd"])) == bytes(h["frame"])


def test_name_derivation_for_user_device():
    key, iv = p.default_key_iv("BLEAPP_847E")  # offset 0x4E
    assert key == bytes(p.KEY_TABLE[(0x4E + i) % 256] for i in range(16))
